/**
 * VERNEN™ Filing Guide View Component
 * © 2024–2026 Michael Vernen Thomas Hartmann. All Rights Reserved.
 * VERNEN™ is a trademark of Michael Vernen Thomas Hartmann.
 *
 * React component for rendering filing guides generated by FilingGuideGenerator.
 */

import React, { useState, useMemo } from "react";

const SEVERITY_COLORS = {
  emergency: { bg: "#fef2f2", border: "#ef4444", text: "#991b1b", badge: "#dc2626" },
  required: { bg: "#fffbeb", border: "#f59e0b", text: "#92400e", badge: "#d97706" },
  recommended: { bg: "#eff6ff", border: "#3b82f6", text: "#1e40af", badge: "#2563eb" },
  info: { bg: "#f0fdf4", border: "#22c55e", text: "#166534", badge: "#16a34a" },
};

export default function FilingGuideView({ guide, onStepComplete, onPrint }) {
  const [expandedSections, setExpandedSections] = useState(new Set(["steps", "fees"]));
  const [completedSteps, setCompletedSteps] = useState(new Set());
  const [showEmergency, setShowEmergency] = useState(!!guide?.emergencyInfo);

  if (!guide || guide.error) {
    return (
      <div style={{ padding: 24, background: "#fef2f2", borderRadius: 8, border: "1px solid #fca5a5" }}>
        <p style={{ color: "#991b1b", fontWeight: 600 }}>⚠️ {guide?.message || "No filing guide available."}</p>
      </div>
    );
  }

  const progress = useMemo(() => {
    const total = guide.filingSteps?.length || 0;
    const done = completedSteps.size;
    return total > 0 ? Math.round((done / total) * 100) : 0;
  }, [completedSteps, guide.filingSteps]);

  const toggleSection = (section) => {
    setExpandedSections((prev) => {
      const next = new Set(prev);
      next.has(section) ? next.delete(section) : next.add(section);
      return next;
    });
  };

  const toggleStep = (stepNum) => {
    setCompletedSteps((prev) => {
      const next = new Set(prev);
      next.has(stepNum) ? next.delete(stepNum) : next.add(stepNum);
      if (onStepComplete) onStepComplete(stepNum, !prev.has(stepNum));
      return next;
    });
  };

  const SectionHeader = ({ id, title, icon, count }) => (
    <button
      onClick={() => toggleSection(id)}
      style={{
        width: "100%", display: "flex", alignItems: "center", justifyContent: "space-between",
        padding: "12px 16px", background: "#f8fafc", border: "1px solid #e2e8f0",
        borderRadius: 8, cursor: "pointer", fontSize: 16, fontWeight: 600, color: "#1e293b",
      }}
    >
      <span>{icon} {title} {count != null && <span style={{ color: "#64748b", fontWeight: 400 }}>({count})</span>}</span>
      <span style={{ transform: expandedSections.has(id) ? "rotate(180deg)" : "rotate(0)", transition: "transform 0.2s" }}>▼</span>
    </button>
  );

  return (
    <div style={{ maxWidth: 800, margin: "0 auto", fontFamily: "'Inter', -apple-system, sans-serif", color: "#1e293b" }}>
      {/* Header */}
      <div style={{ background: "linear-gradient(135deg, #1e3a5f, #2563eb)", borderRadius: 12, padding: 24, color: "#fff", marginBottom: 20 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
          <div>
            <h1 style={{ margin: 0, fontSize: 22, fontWeight: 700 }}>📋 Filing Guide: {guide.meta.formId}</h1>
            <p style={{ margin: "8px 0 0", opacity: 0.9, fontSize: 14 }}>{guide.court.courtName}</p>
            <p style={{ margin: "4px 0 0", opacity: 0.7, fontSize: 12 }}>{guide.court.address}</p>
          </div>
          {onPrint && (
            <button onClick={onPrint} style={{ background: "rgba(255,255,255,0.15)", border: "1px solid rgba(255,255,255,0.3)", color: "#fff", borderRadius: 6, padding: "8px 16px", cursor: "pointer", fontSize: 13 }}>
              🖨️ Print Guide
            </button>
          )}
        </div>

        {/* Progress bar */}
        <div style={{ marginTop: 16 }}>
          <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, opacity: 0.9, marginBottom: 4 }}>
            <span>Filing Progress</span>
            <span>{progress}% ({completedSteps.size}/{guide.filingSteps?.length || 0} steps)</span>
          </div>
          <div style={{ background: "rgba(255,255,255,0.2)", borderRadius: 4, height: 8, overflow: "hidden" }}>
            <div style={{ background: progress === 100 ? "#22c55e" : "#fff", width: `${progress}%`, height: "100%", borderRadius: 4, transition: "width 0.5s ease" }} />
          </div>
        </div>
      </div>

      {/* Emergency Alert */}
      {guide.emergencyInfo && showEmergency && (
        <div style={{ background: SEVERITY_COLORS.emergency.bg, border: `2px solid ${SEVERITY_COLORS.emergency.border}`, borderRadius: 8, padding: 16, marginBottom: 16 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <h3 style={{ margin: 0, color: SEVERITY_COLORS.emergency.text }}>🚨 {guide.emergencyInfo.title}</h3>
            <button onClick={() => setShowEmergency(false)} style={{ background: "none", border: "none", cursor: "pointer", fontSize: 18 }}>×</button>
          </div>
          <p style={{ color: SEVERITY_COLORS.emergency.text, fontWeight: 500, margin: "8px 0" }}>{guide.emergencyInfo.warning}</p>
          <ol style={{ margin: "8px 0", paddingLeft: 20, color: SEVERITY_COLORS.emergency.text }}>
            {guide.emergencyInfo.steps.map((s, i) => <li key={i} style={{ marginBottom: 4 }}>{s}</li>)}
          </ol>
          <p style={{ margin: "8px 0 0", fontSize: 12, color: "#6b7280" }}>
            Court Phone: {guide.emergencyInfo.courtPhone} | Statute: {guide.emergencyInfo.statute}
          </p>
          {guide.emergencyInfo.dvSpecific && (
            <p style={{ margin: "8px 0 0", fontWeight: 600, color: SEVERITY_COLORS.emergency.text }}>{guide.emergencyInfo.dvSpecific}</p>
          )}
        </div>
      )}

      {/* Court Info */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginBottom: 16 }}>
        <div style={{ background: "#f8fafc", borderRadius: 8, padding: 16, border: "1px solid #e2e8f0" }}>
          <h4 style={{ margin: "0 0 8px", color: "#475569", fontSize: 12, textTransform: "uppercase", letterSpacing: "0.05em" }}>Filing Method</h4>
          <p style={{ margin: 0, fontWeight: 600 }}>{guide.court.filingMethod}</p>
          {guide.court.efilingAvailable && (
            <a href={guide.court.efilingUrl} target="_blank" rel="noopener noreferrer" style={{ fontSize: 13, color: "#2563eb" }}>
              E-Filing Portal →
            </a>
          )}
        </div>
        <div style={{ background: "#f8fafc", borderRadius: 8, padding: 16, border: "1px solid #e2e8f0" }}>
          <h4 style={{ margin: "0 0 8px", color: "#475569", fontSize: 12, textTransform: "uppercase", letterSpacing: "0.05em" }}>Filing Fee</h4>
          <p style={{ margin: 0, fontWeight: 600, fontSize: 20 }}>{guide.fees.amount === 0 ? "FREE" : `$${guide.fees.amount}`}</p>
          {guide.fees.feeWaiverApplied && <span style={{ fontSize: 12, color: "#16a34a", fontWeight: 500 }}>✓ Fee Waiver Applied</span>}
          <p style={{ margin: "4px 0 0", fontSize: 12, color: "#6b7280" }}>{guide.fees.statute}</p>
        </div>
      </div>

      {/* Filing Steps */}
      <div style={{ marginBottom: 16 }}>
        <SectionHeader id="steps" title="Filing Steps" icon="📝" count={guide.filingSteps?.length} />
        {expandedSections.has("steps") && (
          <div style={{ padding: "12px 0" }}>
            {(guide.filingSteps || []).map((step) => (
              <div key={step.step}
                onClick={() => toggleStep(step.step)}
                style={{
                  display: "flex", alignItems: "flex-start", gap: 12, padding: "12px 16px",
                  marginBottom: 4, borderRadius: 6, cursor: "pointer",
                  background: completedSteps.has(step.step) ? "#f0fdf4" : "#fff",
                  border: `1px solid ${completedSteps.has(step.step) ? "#86efac" : "#e2e8f0"}`,
                  transition: "all 0.2s",
                }}>
                <div style={{
                  width: 28, height: 28, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center",
                  background: completedSteps.has(step.step) ? "#22c55e" : "#e2e8f0",
                  color: completedSteps.has(step.step) ? "#fff" : "#64748b",
                  fontWeight: 700, fontSize: 13, flexShrink: 0,
                }}>
                  {completedSteps.has(step.step) ? "✓" : step.step}
                </div>
                <div style={{ flex: 1 }}>
                  <p style={{ margin: 0, fontWeight: 600, fontSize: 14, textDecoration: completedSteps.has(step.step) ? "line-through" : "none", color: completedSteps.has(step.step) ? "#6b7280" : "#1e293b" }}>
                    {step.icon} {step.label}
                  </p>
                  {step.details && <p style={{ margin: "4px 0 0", fontSize: 13, color: "#64748b" }}>{step.details}</p>}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Service Requirements */}
      {guide.service && guide.service.method !== "check_local_rules" && (
        <div style={{ marginBottom: 16 }}>
          <SectionHeader id="service" title="Service Requirements" icon="📬" />
          {expandedSections.has("service") && (
            <div style={{ padding: 16, background: SEVERITY_COLORS.required.bg, border: `1px solid ${SEVERITY_COLORS.required.border}`, borderRadius: 8, marginTop: 8 }}>
              <p style={{ margin: "0 0 8px", fontWeight: 600 }}>{guide.service.description}</p>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, fontSize: 13 }}>
                <div><span style={{ color: "#6b7280" }}>Method:</span> <strong>{guide.service.method.replace(/_/g, " ")}</strong></div>
                <div><span style={{ color: "#6b7280" }}>Response Deadline:</span> <strong>{guide.service.responseDeadline} days</strong></div>
                <div><span style={{ color: "#6b7280" }}>Proof Form:</span> <strong>{guide.service.proofOfServiceForm}</strong></div>
                <div><span style={{ color: "#6b7280" }}>Statute:</span> <strong>{guide.service.statute}</strong></div>
              </div>
              {guide.service.notes && <p style={{ margin: "8px 0 0", fontSize: 13, color: "#92400e", fontStyle: "italic" }}>💡 {guide.service.notes}</p>}
              {guide.service.alternatives?.length > 0 && (
                <p style={{ margin: "8px 0 0", fontSize: 12, color: "#6b7280" }}>
                  Alternatives: {guide.service.alternatives.map((a) => a.replace(/_/g, " ")).join(", ")}
                </p>
              )}
            </div>
          )}
        </div>
      )}

      {/* Deadlines */}
      {guide.deadlines?.length > 0 && (
        <div style={{ marginBottom: 16 }}>
          <SectionHeader id="deadlines" title="Critical Deadlines" icon="⏰" count={guide.deadlines.length} />
          {expandedSections.has("deadlines") && (
            <div style={{ padding: "12px 0" }}>
              {guide.deadlines.map((dl, i) => (
                <div key={i} style={{ display: "flex", gap: 12, alignItems: "center", padding: "10px 16px", marginBottom: 4, borderRadius: 6, background: dl.type === "emergency" ? SEVERITY_COLORS.emergency.bg : "#fff", border: `1px solid ${dl.type === "emergency" ? SEVERITY_COLORS.emergency.border : "#e2e8f0"}` }}>
                  <span style={{ background: dl.type === "emergency" ? SEVERITY_COLORS.emergency.badge : SEVERITY_COLORS.required.badge, color: "#fff", borderRadius: 4, padding: "2px 8px", fontSize: 11, fontWeight: 700, textTransform: "uppercase" }}>
                    {dl.calendarType.replace(/_/g, " ")}
                  </span>
                  <div style={{ flex: 1 }}>
                    <p style={{ margin: 0, fontWeight: 500, fontSize: 14 }}>{dl.description}</p>
                    <p style={{ margin: "2px 0 0", fontSize: 12, color: "#6b7280" }}>{dl.statute}</p>
                  </div>
                  <span style={{ fontWeight: 700, fontSize: 18, color: dl.days <= 5 ? "#dc2626" : "#1e293b" }}>
                    {dl.days === 0 ? "NOW" : `${dl.days}d`}
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Companion Forms */}
      {guide.companionForms?.length > 0 && (
        <div style={{ marginBottom: 16 }}>
          <SectionHeader id="companions" title="Companion Forms" icon="📎" count={guide.companionForms.length} />
          {expandedSections.has("companions") && (
            <div style={{ padding: "12px 0" }}>
              {guide.companionForms.map((cf, i) => (
                <div key={i} style={{ display: "flex", gap: 8, alignItems: "center", padding: "8px 16px", marginBottom: 4, borderRadius: 6, background: "#fff", border: `1px solid ${cf.required ? "#f59e0b" : "#e2e8f0"}` }}>
                  <span style={{ background: cf.required ? "#f59e0b" : "#94a3b8", color: "#fff", borderRadius: 4, padding: "2px 6px", fontSize: 10, fontWeight: 700 }}>
                    {cf.required ? "REQUIRED" : "OPTIONAL"}
                  </span>
                  <span style={{ fontWeight: 600, fontSize: 14 }}>{cf.formId}</span>
                  <span style={{ color: "#64748b", fontSize: 13 }}>— {cf.description}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Pro Se Tips */}
      {guide.proSeTips && (
        <div style={{ marginBottom: 16 }}>
          <SectionHeader id="tips" title="Pro Se Tips" icon="💡" />
          {expandedSections.has("tips") && (
            <div style={{ padding: 16, background: SEVERITY_COLORS.info.bg, border: `1px solid ${SEVERITY_COLORS.info.border}`, borderRadius: 8, marginTop: 8 }}>
              <h4 style={{ margin: "0 0 8px", fontSize: 13, color: "#166534", textTransform: "uppercase" }}>Universal Tips</h4>
              {guide.proSeTips.universal.map((tip, i) => (
                <p key={i} style={{ margin: "4px 0", fontSize: 13, color: "#166534" }}>✓ {tip}</p>
              ))}
              {guide.proSeTips.formSpecific?.length > 0 && (
                <>
                  <h4 style={{ margin: "12px 0 8px", fontSize: 13, color: "#166534", textTransform: "uppercase" }}>
                    {guide.meta.formId}-Specific Tips
                  </h4>
                  {guide.proSeTips.formSpecific.map((tip, i) => (
                    <p key={i} style={{ margin: "4px 0", fontSize: 13, color: "#166534" }}>⭐ {tip}</p>
                  ))}
                </>
              )}
            </div>
          )}
        </div>
      )}

      {/* Court Contact */}
      <div style={{ background: "#f1f5f9", borderRadius: 8, padding: 16, border: "1px solid #cbd5e1" }}>
        <h4 style={{ margin: "0 0 8px", fontSize: 13, color: "#475569", textTransform: "uppercase" }}>Court Contact Information</h4>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, fontSize: 13 }}>
          <div><span style={{ color: "#6b7280" }}>Clerk:</span> {guide.court.clerkPhone}</div>
          <div><span style={{ color: "#6b7280" }}>Hours:</span> {guide.court.filingHours}</div>
          {guide.court.selfHelpCenter && (
            <div><span style={{ color: "#6b7280" }}>Self-Help:</span> {guide.court.selfHelpPhone}</div>
          )}
        </div>
      </div>

      {/* Footer */}
      <div style={{ marginTop: 16, padding: 12, textAlign: "center", fontSize: 11, color: "#94a3b8" }}>
        <p style={{ margin: 0 }}>Generated by VERNEN™ Filing Guide Generator</p>
        <p style={{ margin: "2px 0 0" }}>© 2024–2026 Michael Vernen Thomas Hartmann. All Rights Reserved.</p>
        <p style={{ margin: "2px 0 0" }}>This guide is for informational purposes only. Consult an attorney for legal advice.</p>
      </div>
    </div>
  );
}
