/**
 * VERNEN™ Audit Report Generator
 * © 2024–2026 Michael Vernen Thomas Hartmann. All Rights Reserved.
 * VERNEN™ is a trademark of Michael Vernen Thomas Hartmann.
 *
 * Generates structured compliance audit reports combining
 * validation results, filing guide data, and risk assessment
 * into exportable professional reports.
 */

const RISK_LEVELS = {
  CRITICAL: { label: 'Critical', color: '#ef4444', weight: 4, description: 'Immediate action required. Filing may be rejected or rights may be forfeited.' },
  HIGH: { label: 'High', color: '#f97316', weight: 3, description: 'Significant compliance issue. Should be resolved before filing.' },
  MEDIUM: { label: 'Medium', color: '#f59e0b', weight: 2, description: 'Potential issue that may affect proceedings.' },
  LOW: { label: 'Low', color: '#22c55e', weight: 1, description: 'Minor concern. Recommended improvement.' },
  INFO: { label: 'Info', color: '#3b82f6', weight: 0, description: 'Informational note for reference.' },
};

const AUDIT_CATEGORIES = {
  COMPLETENESS: { label: 'Form Completeness', icon: '☑', description: 'All required fields populated with valid data' },
  ACCURACY: { label: 'Data Accuracy', icon: '⊕', description: 'Information is consistent and factually correct' },
  COMPLIANCE: { label: 'Legal Compliance', icon: '§', description: 'Adherence to statutory requirements and court rules' },
  SERVICE: { label: 'Service Requirements', icon: '⟐', description: 'Proper service method and timeline compliance' },
  DEADLINES: { label: 'Filing Deadlines', icon: '⏰', description: 'All critical deadlines identified and met' },
  CROSS_FORM: { label: 'Cross-Form Consistency', icon: '⇄', description: 'Data consistency across companion forms' },
  PROCEDURAL: { label: 'Procedural Compliance', icon: '⊞', description: 'Court-specific procedural requirements met' },
};

/**
 * Generate a comprehensive audit report
 */
function generateReport({ formId, formData, validationResults, filingGuide, options = {} }) {
  const { includeRecommendations = true, includeTimeline = true, reportFormat = 'full' } = options;

  const report = {
    meta: {
      reportId: generateReportId(),
      formId,
      generatedAt: new Date().toISOString(),
      generatedBy: 'VERNEN™ Audit Report Generator v1.0',
      reportFormat,
      disclaimer: 'This audit report is generated by automated analysis and does not constitute legal advice. All findings should be verified by a qualified legal professional before reliance.',
      copyright: '© 2024–2026 Michael Vernen Thomas Hartmann. All Rights Reserved.',
    },
    summary: buildExecutiveSummary(formId, validationResults, filingGuide),
    riskAssessment: buildRiskAssessment(validationResults),
    findings: buildFindings(validationResults, filingGuide),
    categoryScores: buildCategoryScores(validationResults),
    filingReadiness: assessFilingReadiness(validationResults, filingGuide),
  };

  if (includeRecommendations) {
    report.recommendations = buildRecommendations(report.findings, report.riskAssessment);
  }

  if (includeTimeline && filingGuide?.deadlines) {
    report.deadlineTimeline = buildDeadlineTimeline(filingGuide.deadlines);
  }

  report.auditTrail = buildAuditTrail(formId, formData, validationResults);

  return report;
}

function generateReportId() {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).substring(2, 6);
  return `VERN-AUD-${ts}-${rand}`.toUpperCase();
}

function buildExecutiveSummary(formId, validationResults, filingGuide) {
  const score = validationResults?.score ?? 0;
  const totalFindings = validationResults?.findings?.length ?? 0;
  const criticalCount = validationResults?.findings?.filter((f) => f.severity === 'error').length ?? 0;
  const warningCount = validationResults?.findings?.filter((f) => f.severity === 'warning').length ?? 0;

  let overallStatus;
  if (score >= 90 && criticalCount === 0) {
    overallStatus = 'READY_TO_FILE';
  } else if (score >= 70 && criticalCount === 0) {
    overallStatus = 'NEEDS_REVIEW';
  } else if (criticalCount > 0) {
    overallStatus = 'CRITICAL_ISSUES';
  } else {
    overallStatus = 'NOT_READY';
  }

  return {
    formId,
    formLabel: filingGuide?.meta?.formLabel || formId,
    complianceScore: score,
    overallStatus,
    statusLabel: {
      READY_TO_FILE: 'Ready to File',
      NEEDS_REVIEW: 'Needs Review',
      CRITICAL_ISSUES: 'Critical Issues Found',
      NOT_READY: 'Not Ready to File',
    }[overallStatus],
    totalFindings,
    criticalCount,
    warningCount,
    infoCount: totalFindings - criticalCount - warningCount,
    courtName: filingGuide?.court?.name || 'Not specified',
    filingFee: filingGuide?.fees?.filingFee ?? 'Unknown',
  };
}

function buildRiskAssessment(validationResults) {
  if (!validationResults?.findings) {
    return { overallRisk: 'UNKNOWN', factors: [], riskScore: 0 };
  }

  const factors = [];
  let riskScore = 0;

  // Assess each finding's risk contribution
  for (const finding of validationResults.findings) {
    let level;
    if (finding.severity === 'error') {
      level = finding.rule?.includes('deadline') || finding.rule?.includes('required') ? 'CRITICAL' : 'HIGH';
    } else if (finding.severity === 'warning') {
      level = finding.rule?.includes('cross_form') ? 'MEDIUM' : 'MEDIUM';
    } else {
      level = 'LOW';
    }

    factors.push({
      finding: finding.message || finding.rule,
      riskLevel: level,
      weight: RISK_LEVELS[level].weight,
      category: categorizeFinding(finding),
      mitigationAvailable: true,
    });

    riskScore += RISK_LEVELS[level].weight;
  }

  // Normalize risk score (0-100)
  const maxPossibleRisk = validationResults.findings.length * 4;
  const normalizedRisk = maxPossibleRisk > 0 ? Math.round((riskScore / maxPossibleRisk) * 100) : 0;

  let overallRisk;
  if (normalizedRisk >= 75) overallRisk = 'CRITICAL';
  else if (normalizedRisk >= 50) overallRisk = 'HIGH';
  else if (normalizedRisk >= 25) overallRisk = 'MEDIUM';
  else overallRisk = 'LOW';

  return {
    overallRisk,
    overallRiskLabel: RISK_LEVELS[overallRisk].label,
    overallRiskDescription: RISK_LEVELS[overallRisk].description,
    riskScore: normalizedRisk,
    factors: factors.sort((a, b) => b.weight - a.weight),
    riskDistribution: {
      critical: factors.filter((f) => f.riskLevel === 'CRITICAL').length,
      high: factors.filter((f) => f.riskLevel === 'HIGH').length,
      medium: factors.filter((f) => f.riskLevel === 'MEDIUM').length,
      low: factors.filter((f) => f.riskLevel === 'LOW').length,
    },
  };
}

function buildFindings(validationResults, filingGuide) {
  const findings = [];

  // Validation findings
  if (validationResults?.findings) {
    for (const f of validationResults.findings) {
      findings.push({
        id: `VAL-${findings.length + 1}`,
        source: 'validation',
        category: categorizeFinding(f),
        severity: f.severity || 'info',
        title: f.message || f.rule,
        details: f.details || null,
        field: f.field || null,
        rule: f.rule || null,
        statutoryBasis: f.statutory || null,
        recommendation: generateFindingRecommendation(f),
      });
    }
  }

  // Filing guide warnings
  if (filingGuide?.service?.warnings) {
    for (const warn of filingGuide.service.warnings) {
      findings.push({
        id: `FG-${findings.length + 1}`,
        source: 'filing_guide',
        category: 'SERVICE',
        severity: 'warning',
        title: warn,
        details: null,
        field: null,
        rule: 'service_requirement',
        statutoryBasis: filingGuide.service.statutoryBasis || null,
        recommendation: 'Ensure service is completed properly per statutory requirements.',
      });
    }
  }

  // Deadline findings
  if (filingGuide?.deadlines) {
    for (const d of filingGuide.deadlines) {
      if (d.critical) {
        findings.push({
          id: `DL-${findings.length + 1}`,
          source: 'deadline_check',
          category: 'DEADLINES',
          severity: 'warning',
          title: `Critical Deadline: ${d.event}`,
          details: d.calculation,
          field: null,
          rule: 'deadline_compliance',
          statutoryBasis: d.statutory || null,
          recommendation: `Calendar this deadline and serve/file well in advance. Missing this deadline may result in loss of rights.`,
        });
      }
    }
  }

  return findings.sort((a, b) => {
    const sevOrder = { error: 0, warning: 1, info: 2 };
    return (sevOrder[a.severity] ?? 3) - (sevOrder[b.severity] ?? 3);
  });
}

function categorizeFinding(finding) {
  const rule = (finding.rule || '').toLowerCase();
  const msg = (finding.message || '').toLowerCase();

  if (rule.includes('required') || rule.includes('missing') || msg.includes('incomplete')) return 'COMPLETENESS';
  if (rule.includes('cross_form') || rule.includes('companion')) return 'CROSS_FORM';
  if (rule.includes('deadline') || rule.includes('timeline')) return 'DEADLINES';
  if (rule.includes('service')) return 'SERVICE';
  if (rule.includes('statutory') || rule.includes('code')) return 'COMPLIANCE';
  if (rule.includes('format') || rule.includes('accuracy')) return 'ACCURACY';
  return 'PROCEDURAL';
}

function generateFindingRecommendation(finding) {
  const rule = (finding.rule || '').toLowerCase();

  if (rule.includes('required_field')) return 'Complete this required field before filing. Missing required fields may result in rejection.';
  if (rule.includes('signature')) return 'Ensure the form is signed with blue ink. Unsigned forms will be rejected.';
  if (rule.includes('date')) return 'Verify the date is correct and in the proper format (MM/DD/YYYY).';
  if (rule.includes('case_number')) return 'Verify the case number matches exactly across all forms.';
  if (rule.includes('cross_form')) return 'Ensure data consistency between this form and its companion forms.';
  if (rule.includes('fee_waiver')) return 'If unable to pay fees, file FW-001 concurrently.';

  return 'Review this finding and correct before filing.';
}

function buildCategoryScores(validationResults) {
  const categories = {};

  for (const [key, cat] of Object.entries(AUDIT_CATEGORIES)) {
    categories[key] = {
      ...cat,
      score: 100,
      findingCount: 0,
      criticalCount: 0,
    };
  }

  if (validationResults?.findings) {
    for (const f of validationResults.findings) {
      const cat = categorizeFinding(f);
      if (categories[cat]) {
        categories[cat].findingCount++;
        if (f.severity === 'error') {
          categories[cat].criticalCount++;
          categories[cat].score = Math.max(0, categories[cat].score - 25);
        } else if (f.severity === 'warning') {
          categories[cat].score = Math.max(0, categories[cat].score - 10);
        } else {
          categories[cat].score = Math.max(0, categories[cat].score - 3);
        }
      }
    }
  }

  return categories;
}

function assessFilingReadiness(validationResults, filingGuide) {
  const checks = [];

  // Form completeness
  const score = validationResults?.score ?? 0;
  checks.push({
    check: 'Form Completeness',
    passed: score >= 80,
    detail: `Compliance score: ${score}%`,
  });

  // No critical errors
  const criticals = validationResults?.findings?.filter((f) => f.severity === 'error').length ?? 0;
  checks.push({
    check: 'No Critical Errors',
    passed: criticals === 0,
    detail: criticals > 0 ? `${criticals} critical error(s) found` : 'No critical errors',
  });

  // Fee preparation
  const fee = filingGuide?.fees?.filingFee ?? 0;
  checks.push({
    check: 'Filing Fee Prepared',
    passed: fee === 0 || filingGuide?.fees?.feeWaiverEligible,
    detail: fee > 0 ? `$${fee} required (fee waiver: ${filingGuide?.fees?.feeWaiverEligible ? 'eligible' : 'not eligible'})` : 'No fee required',
  });

  // Service arranged
  const serviceRequired = filingGuide?.service && filingGuide.service.method !== 'none';
  checks.push({
    check: 'Service Arranged',
    passed: !serviceRequired, // default to pending if service needed
    detail: serviceRequired ? `${filingGuide.service.method} service required via ${filingGuide.service.proofOfServiceForm}` : 'No service required',
    requiresManualConfirmation: serviceRequired,
  });

  // Copies prepared
  checks.push({
    check: 'Copies Prepared',
    passed: false,
    detail: 'Minimum 3 copies required (original + 2 stamped copies)',
    requiresManualConfirmation: true,
  });

  const passedCount = checks.filter((c) => c.passed).length;
  const totalChecks = checks.length;
  const readyToFile = checks.filter((c) => !c.requiresManualConfirmation).every((c) => c.passed);

  return {
    readyToFile,
    readinessScore: Math.round((passedCount / totalChecks) * 100),
    checks,
    passedCount,
    totalChecks,
    manualConfirmationsNeeded: checks.filter((c) => c.requiresManualConfirmation && !c.passed).length,
  };
}

function buildRecommendations(findings, riskAssessment) {
  const recs = [];
  const seen = new Set();

  // Priority 1: Critical findings
  for (const f of findings.filter((f) => f.severity === 'error')) {
    const key = f.category + ':' + f.rule;
    if (!seen.has(key)) {
      recs.push({
        priority: 1,
        label: 'URGENT',
        action: f.recommendation,
        relatedFinding: f.id,
        category: f.category,
      });
      seen.add(key);
    }
  }

  // Priority 2: Warnings
  for (const f of findings.filter((f) => f.severity === 'warning')) {
    const key = f.category + ':' + f.rule;
    if (!seen.has(key)) {
      recs.push({
        priority: 2,
        label: 'RECOMMENDED',
        action: f.recommendation,
        relatedFinding: f.id,
        category: f.category,
      });
      seen.add(key);
    }
  }

  // Priority 3: General best practices
  if (riskAssessment.overallRisk === 'CRITICAL' || riskAssessment.overallRisk === 'HIGH') {
    recs.push({
      priority: 3,
      label: 'BEST PRACTICE',
      action: 'Consider visiting the court self-help center for a free review of your forms before filing.',
      relatedFinding: null,
      category: 'PROCEDURAL',
    });
  }

  recs.push({
    priority: 3,
    label: 'BEST PRACTICE',
    action: 'Retain file-stamped copies of all documents. Use blue ink for original signatures.',
    relatedFinding: null,
    category: 'PROCEDURAL',
  });

  return recs.sort((a, b) => a.priority - b.priority);
}

function buildDeadlineTimeline(deadlines) {
  return deadlines.map((d, i) => ({
    order: i + 1,
    event: d.event,
    date: d.date || null,
    calculation: d.calculation || null,
    statutory: d.statutory || null,
    critical: d.critical || false,
    status: d.date && new Date(d.date) < new Date() ? 'PASSED' : 'UPCOMING',
  })).sort((a, b) => {
    if (a.date && b.date) return new Date(a.date) - new Date(b.date);
    return a.critical ? -1 : 1;
  });
}

function buildAuditTrail(formId, formData, validationResults) {
  return {
    auditSteps: [
      { step: 1, action: 'Form data received', timestamp: new Date().toISOString(), status: 'complete' },
      { step: 2, action: 'Validation engine executed', timestamp: new Date().toISOString(), status: validationResults ? 'complete' : 'skipped' },
      { step: 3, action: 'Risk assessment computed', timestamp: new Date().toISOString(), status: 'complete' },
      { step: 4, action: 'Filing readiness evaluated', timestamp: new Date().toISOString(), status: 'complete' },
      { step: 5, action: 'Report generated', timestamp: new Date().toISOString(), status: 'complete' },
    ],
    dataIntegrity: {
      formFieldCount: formData ? Object.keys(formData).length : 0,
      validationRulesChecked: validationResults?.rulesChecked || 0,
      findingsGenerated: validationResults?.findings?.length || 0,
    },
  };
}

/**
 * Generate a multi-form package audit report
 */
function generatePackageReport(formPackages) {
  const reports = formPackages.map((pkg) => generateReport(pkg));

  const packageSummary = {
    totalForms: reports.length,
    overallScore: Math.round(reports.reduce((sum, r) => sum + (r.summary.complianceScore || 0), 0) / reports.length),
    totalFindings: reports.reduce((sum, r) => sum + r.summary.totalFindings, 0),
    totalCritical: reports.reduce((sum, r) => sum + r.summary.criticalCount, 0),
    allReady: reports.every((r) => r.filingReadiness.readyToFile),
  };

  return { packageSummary, reports };
}

export { generateReport, generatePackageReport, RISK_LEVELS, AUDIT_CATEGORIES };
export default generateReport;
