/**
 * VERNEN™ Export Engine
 * © 2024–2026 Michael Vernen Thomas Hartmann. All Rights Reserved.
 * VERNEN™ is a trademark of Michael Vernen Thomas Hartmann.
 *
 * Multi-format export engine supporting HTML (print-ready), JSON, CSV,
 * Markdown, and PDF-ready markup for all VERNEN module outputs.
 */

// ─── FORMAT DEFINITIONS ────────────────────────────────────────────
const EXPORT_FORMATS = {
  HTML: 'html',
  JSON: 'json',
  CSV: 'csv',
  MARKDOWN: 'markdown',
  TEXT: 'text'
};

const MODULE_TYPES = {
  FORM_DATA: 'form_data',
  VALIDATION_REPORT: 'validation_report',
  FILING_GUIDE: 'filing_guide',
  AUDIT_REPORT: 'audit_report',
  ASSEMBLY_PACKAGE: 'assembly_package'
};

// ─── HTML TEMPLATE ─────────────────────────────────────────────────
const HTML_TEMPLATE = `<!DOCTYPE html>
<html lang="{{lang}}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{title}} — VERNEN™</title>
<style>
  @page {
    size: letter;
    margin: 0.75in;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.5;
    color: #1a1a1a;
    padding: 0.5in;
  }
  .header {
    border-bottom: 2px solid #1a3a5c;
    padding-bottom: 12px;
    margin-bottom: 24px;
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
  }
  .header-title {
    font-size: 18pt;
    font-weight: 700;
    color: #1a3a5c;
  }
  .header-subtitle {
    font-size: 10pt;
    color: #666;
  }
  .header-meta {
    text-align: right;
    font-size: 9pt;
    color: #666;
  }
  h2 { font-size: 14pt; color: #1a3a5c; margin: 20px 0 10px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
  h3 { font-size: 12pt; color: #2c5282; margin: 16px 0 8px; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 10pt; }
  th { background: #f0f4f8; color: #1a3a5c; text-align: left; padding: 8px; border: 1px solid #d0d5dd; font-weight: 600; }
  td { padding: 6px 8px; border: 1px solid #e0e0e0; vertical-align: top; }
  tr:nth-child(even) { background: #fafbfc; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 3px; font-size: 9pt; font-weight: 600; }
  .badge-critical { background: #fee2e2; color: #991b1b; }
  .badge-high { background: #fff3cd; color: #856404; }
  .badge-medium { background: #e0f2fe; color: #075985; }
  .badge-low { background: #d1fae5; color: #065f46; }
  .badge-pass { background: #d1fae5; color: #065f46; }
  .badge-fail { background: #fee2e2; color: #991b1b; }
  .score-circle {
    display: inline-flex; align-items: center; justify-content: center;
    width: 60px; height: 60px; border-radius: 50%; font-size: 18pt;
    font-weight: 700; color: white;
  }
  .score-high { background: #059669; }
  .score-medium { background: #d97706; }
  .score-low { background: #dc2626; }
  .footer {
    margin-top: 40px;
    padding-top: 12px;
    border-top: 1px solid #ddd;
    font-size: 8pt;
    color: #999;
    text-align: center;
  }
  .section { margin-bottom: 24px; page-break-inside: avoid; }
  .field-row { display: flex; margin: 4px 0; }
  .field-label { font-weight: 600; min-width: 200px; color: #444; }
  .field-value { flex: 1; }
  .checklist-item { padding: 4px 0; }
  .checklist-item::before { content: '☐ '; }
  .checklist-item.checked::before { content: '☑ '; color: #059669; }
  @media print {
    body { padding: 0; }
    .no-print { display: none; }
  }
</style>
</head>
<body>
{{content}}
<div class="footer">
  Generated by VERNEN™ Legal Compliance Platform — {{timestamp}}<br>
  © 2024–2026 Michael Vernen Thomas Hartmann. All Rights Reserved.
  <span class="no-print"> | This document was generated for informational purposes only and does not constitute legal advice.</span>
</div>
</body>
</html>`;

// ─── EXPORT ENGINE ─────────────────────────────────────────────────
class ExportEngine {
  constructor(config = {}) {
    this.config = {
      language: config.language || 'en',
      includeTimestamp: config.includeTimestamp !== false,
      includeBranding: config.includeBranding !== false,
      piiMasking: config.piiMasking || false,
      ...config
    };
    this.PII_FIELDS = new Set([
      'petitioner_name', 'respondent_name', 'child_name', 'child_dob',
      'ssn', 'date_of_birth', 'address', 'phone', 'email', 'income'
    ]);
  }

  // ── Main Export Dispatch ────────────────────────────────────────
  export(data, moduleType, format, options = {}) {
    const merged = { ...this.config, ...options };
    const processed = this.config.piiMasking ? this._maskPII(data) : data;

    switch (format) {
      case EXPORT_FORMATS.HTML: return this._toHTML(processed, moduleType, merged);
      case EXPORT_FORMATS.JSON: return this._toJSON(processed, moduleType, merged);
      case EXPORT_FORMATS.CSV: return this._toCSV(processed, moduleType, merged);
      case EXPORT_FORMATS.MARKDOWN: return this._toMarkdown(processed, moduleType, merged);
      case EXPORT_FORMATS.TEXT: return this._toText(processed, moduleType, merged);
      default: throw new Error(`Unsupported export format: ${format}`);
    }
  }

  // ── HTML Export ─────────────────────────────────────────────────
  _toHTML(data, moduleType, options) {
    let content = '';
    const title = this._getTitle(data, moduleType);

    content += `<div class="header">
      <div><div class="header-title">${this._esc(title)}</div>
      <div class="header-subtitle">${this._getSubtitle(data, moduleType)}</div></div>
      <div class="header-meta">
        ${options.includeTimestamp ? `Generated: ${new Date().toLocaleString()}<br>` : ''}
        ${data.caseNumber ? `Case: ${this._esc(data.caseNumber)}<br>` : ''}
        ${data.county ? `County: ${this._esc(data.county)}` : ''}
      </div>
    </div>`;

    switch (moduleType) {
      case MODULE_TYPES.FORM_DATA:
        content += this._formDataToHTML(data); break;
      case MODULE_TYPES.VALIDATION_REPORT:
        content += this._validationToHTML(data); break;
      case MODULE_TYPES.FILING_GUIDE:
        content += this._filingGuideToHTML(data); break;
      case MODULE_TYPES.AUDIT_REPORT:
        content += this._auditReportToHTML(data); break;
      case MODULE_TYPES.ASSEMBLY_PACKAGE:
        content += this._assemblyToHTML(data); break;
      default:
        content += this._genericToHTML(data);
    }

    return HTML_TEMPLATE
      .replace('{{lang}}', options.language)
      .replace('{{title}}', this._esc(title))
      .replace('{{content}}', content)
      .replace('{{timestamp}}', new Date().toISOString());
  }

  _formDataToHTML(data) {
    let html = '<div class="section"><h2>Form Data</h2>';
    const fields = data.fields || data;
    for (const [key, value] of Object.entries(fields)) {
      if (key.startsWith('__')) continue;
      html += `<div class="field-row">
        <span class="field-label">${this._fieldLabel(key)}</span>
        <span class="field-value">${this._esc(String(value || '—'))}</span>
      </div>`;
    }
    html += '</div>';
    return html;
  }

  _validationToHTML(data) {
    let html = '';
    const score = data.score ?? data.complianceScore ?? 0;
    const scoreClass = score >= 80 ? 'score-high' : score >= 50 ? 'score-medium' : 'score-low';

    html += `<div class="section"><h2>Compliance Score</h2>
      <div class="score-circle ${scoreClass}">${score}%</div>
      <span style="margin-left:12px;font-size:14pt;font-weight:600;">${
        score >= 80 ? 'Ready to File' : score >= 50 ? 'Needs Attention' : 'Not Ready'
      }</span></div>`;

    if (data.errors?.length) {
      html += '<div class="section"><h2>Errors</h2><table><tr><th>Field</th><th>Issue</th><th>Severity</th></tr>';
      data.errors.forEach(e => {
        html += `<tr><td>${this._esc(e.field || '—')}</td><td>${this._esc(e.message)}</td>
          <td><span class="badge badge-critical">${e.severity || 'ERROR'}</span></td></tr>`;
      });
      html += '</table></div>';
    }

    if (data.warnings?.length) {
      html += '<div class="section"><h2>Warnings</h2><table><tr><th>Field</th><th>Issue</th></tr>';
      data.warnings.forEach(w => {
        html += `<tr><td>${this._esc(w.field || '—')}</td><td>${this._esc(w.message)}</td></tr>`;
      });
      html += '</table></div>';
    }
    return html;
  }

  _filingGuideToHTML(data) {
    let html = '';
    if (data.courtInfo) {
      html += `<div class="section"><h2>Court Information</h2>
        <div class="field-row"><span class="field-label">Court</span><span class="field-value">${this._esc(data.courtInfo.name || '')}</span></div>
        <div class="field-row"><span class="field-label">Address</span><span class="field-value">${this._esc(data.courtInfo.address || '')}</span></div>
        <div class="field-row"><span class="field-label">E-Filing</span><span class="field-value">${data.courtInfo.efiling ? 'Available' : 'Not Available'}</span></div>
      </div>`;
    }
    if (data.checklist?.length) {
      html += '<div class="section"><h2>Filing Checklist</h2>';
      data.checklist.forEach(item => {
        html += `<div class="checklist-item${item.completed ? ' checked' : ''}">${this._esc(item.label || item)}</div>`;
      });
      html += '</div>';
    }
    if (data.fees) {
      html += '<div class="section"><h2>Fee Schedule</h2><table><tr><th>Item</th><th>Amount</th><th>Waivable</th></tr>';
      for (const [item, info] of Object.entries(data.fees)) {
        const fee = typeof info === 'object' ? info : { amount: info };
        html += `<tr><td>${this._esc(item)}</td><td>$${fee.amount || 0}</td>
          <td>${fee.waivable ? '<span class="badge badge-pass">Yes</span>' : 'No'}</td></tr>`;
      }
      html += '</table></div>';
    }
    return html;
  }

  _auditReportToHTML(data) {
    let html = '';
    if (data.executive) {
      const s = data.executive;
      const sc = (s.complianceScore || 0);
      const cls = sc >= 80 ? 'score-high' : sc >= 50 ? 'score-medium' : 'score-low';
      html += `<div class="section"><h2>Executive Summary</h2>
        <div class="score-circle ${cls}">${sc}%</div>
        <span style="margin-left:12px;font-size:12pt;">${this._esc(s.status || '')}</span>
        <p style="margin-top:12px;">${this._esc(s.summary || '')}</p></div>`;
    }
    if (data.findings?.length) {
      html += '<div class="section"><h2>Findings</h2><table><tr><th>#</th><th>Category</th><th>Finding</th><th>Risk</th></tr>';
      data.findings.forEach((f, i) => {
        const badge = (f.risk || f.severity || 'info').toLowerCase();
        html += `<tr><td>${i + 1}</td><td>${this._esc(f.category || '')}</td>
          <td>${this._esc(f.message || f.description || '')}</td>
          <td><span class="badge badge-${badge}">${(f.risk || f.severity || 'INFO').toUpperCase()}</span></td></tr>`;
      });
      html += '</table></div>';
    }
    if (data.recommendations?.length) {
      html += '<div class="section"><h2>Recommendations</h2><table><tr><th>Priority</th><th>Action</th></tr>';
      data.recommendations.forEach(r => {
        html += `<tr><td><span class="badge badge-${(r.priority || 'medium').toLowerCase()}">${(r.priority || 'MEDIUM').toUpperCase()}</span></td>
          <td>${this._esc(r.action || r.text || r)}</td></tr>`;
      });
      html += '</table></div>';
    }
    return html;
  }

  _assemblyToHTML(data) {
    let html = '<div class="section"><h2>Document Assembly Package</h2>';
    if (data.forms?.length) {
      html += '<table><tr><th>Form</th><th>Title</th><th>Fields Populated</th><th>Status</th></tr>';
      data.forms.forEach(f => {
        html += `<tr><td>${this._esc(f.formId || '')}</td><td>${this._esc(f.title || '')}</td>
          <td>${f.populatedFields || 0} / ${f.totalFields || 0}</td>
          <td><span class="badge badge-${f.ready ? 'pass' : 'fail'}">${f.ready ? 'Ready' : 'Incomplete'}</span></td></tr>`;
      });
      html += '</table>';
    }
    html += '</div>';
    return html;
  }

  _genericToHTML(data) {
    return `<div class="section"><pre>${this._esc(JSON.stringify(data, null, 2))}</pre></div>`;
  }

  // ── JSON Export ─────────────────────────────────────────────────
  _toJSON(data, moduleType, options) {
    return JSON.stringify({
      meta: {
        platform: 'VERNEN',
        version: '1.0.0',
        moduleType,
        exportedAt: new Date().toISOString(),
        language: options.language
      },
      data
    }, null, 2);
  }

  // ── CSV Export ──────────────────────────────────────────────────
  _toCSV(data, moduleType, options) {
    let rows = [];
    switch (moduleType) {
      case MODULE_TYPES.FORM_DATA: {
        const fields = data.fields || data;
        rows.push(['Field', 'Value']);
        Object.entries(fields).filter(([k]) => !k.startsWith('__')).forEach(([k, v]) => {
          rows.push([this._fieldLabel(k), String(v || '')]);
        });
        break;
      }
      case MODULE_TYPES.VALIDATION_REPORT: {
        rows.push(['Type', 'Field', 'Message', 'Severity']);
        (data.errors || []).forEach(e => rows.push(['Error', e.field || '', e.message, e.severity || 'ERROR']));
        (data.warnings || []).forEach(w => rows.push(['Warning', w.field || '', w.message, 'WARNING']));
        break;
      }
      case MODULE_TYPES.AUDIT_REPORT: {
        rows.push(['#', 'Category', 'Finding', 'Risk Level']);
        (data.findings || []).forEach((f, i) => rows.push([i + 1, f.category || '', f.message || f.description || '', f.risk || f.severity || '']));
        break;
      }
      default: {
        rows.push(['Key', 'Value']);
        this._flattenObj(data).forEach(([k, v]) => rows.push([k, String(v)]));
      }
    }
    return rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n');
  }

  // ── Markdown Export ─────────────────────────────────────────────
  _toMarkdown(data, moduleType, options) {
    const title = this._getTitle(data, moduleType);
    let md = `# ${title}\n\n`;
    if (options.includeTimestamp) md += `*Generated: ${new Date().toLocaleString()}*\n\n`;

    switch (moduleType) {
      case MODULE_TYPES.FORM_DATA: {
        md += '## Form Data\n\n';
        const fields = data.fields || data;
        Object.entries(fields).filter(([k]) => !k.startsWith('__')).forEach(([k, v]) => {
          md += `- **${this._fieldLabel(k)}:** ${v || '—'}\n`;
        });
        break;
      }
      case MODULE_TYPES.VALIDATION_REPORT: {
        const score = data.score ?? data.complianceScore ?? 0;
        md += `## Compliance Score: ${score}%\n\n`;
        if (data.errors?.length) {
          md += '## Errors\n\n| Field | Issue | Severity |\n|-------|-------|----------|\n';
          data.errors.forEach(e => md += `| ${e.field || '—'} | ${e.message} | ${e.severity || 'ERROR'} |\n`);
        }
        if (data.warnings?.length) {
          md += '\n## Warnings\n\n| Field | Issue |\n|-------|-------|\n';
          data.warnings.forEach(w => md += `| ${w.field || '—'} | ${w.message} |\n`);
        }
        break;
      }
      case MODULE_TYPES.AUDIT_REPORT: {
        if (data.executive) md += `## Executive Summary\n\n**Score:** ${data.executive.complianceScore || 0}%\n**Status:** ${data.executive.status || 'N/A'}\n\n`;
        if (data.findings?.length) {
          md += '## Findings\n\n| # | Category | Finding | Risk |\n|---|----------|---------|------|\n';
          data.findings.forEach((f, i) => md += `| ${i + 1} | ${f.category || ''} | ${f.message || f.description || ''} | ${f.risk || f.severity || ''} |\n`);
        }
        if (data.recommendations?.length) {
          md += '\n## Recommendations\n\n';
          data.recommendations.forEach(r => md += `- **[${(r.priority || 'MEDIUM').toUpperCase()}]** ${r.action || r.text || r}\n`);
        }
        break;
      }
      default:
        md += '```json\n' + JSON.stringify(data, null, 2) + '\n```\n';
    }

    if (options.includeBranding) md += '\n---\n*Generated by VERNEN™ — © 2024–2026 Michael Vernen Thomas Hartmann*\n';
    return md;
  }

  // ── Text Export ─────────────────────────────────────────────────
  _toText(data, moduleType, options) {
    const md = this._toMarkdown(data, moduleType, options);
    return md.replace(/[#*|`_\[\]]/g, '').replace(/---/g, '─'.repeat(60)).replace(/\n{3,}/g, '\n\n');
  }

  // ── Download Trigger ────────────────────────────────────────────
  download(content, filename, mimeType = 'text/plain') {
    if (typeof document === 'undefined') return content;
    const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    return content;
  }

  exportAndDownload(data, moduleType, format, filename = null) {
    const content = this.export(data, moduleType, format);
    const ext = { html: 'html', json: 'json', csv: 'csv', markdown: 'md', text: 'txt' }[format] || 'txt';
    const mime = { html: 'text/html', json: 'application/json', csv: 'text/csv', markdown: 'text/markdown', text: 'text/plain' }[format] || 'text/plain';
    const fn = filename || `vernen_${moduleType}_${Date.now()}.${ext}`;
    return this.download(content, fn, mime);
  }

  // ── Print ───────────────────────────────────────────────────────
  print(data, moduleType, options = {}) {
    const html = this._toHTML(data, moduleType, options);
    if (typeof window === 'undefined') return html;
    const printWindow = window.open('', '_blank');
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 500);
    return html;
  }

  // ── Utilities ───────────────────────────────────────────────────
  _esc(str) { return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }

  _fieldLabel(key) {
    return key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  }

  _getTitle(data, moduleType) {
    if (data.title) return data.title;
    const titles = {
      [MODULE_TYPES.FORM_DATA]: `Form Data — ${data.formId || 'Unknown'}`,
      [MODULE_TYPES.VALIDATION_REPORT]: `Validation Report — ${data.formId || 'Unknown'}`,
      [MODULE_TYPES.FILING_GUIDE]: `Filing Guide — ${data.formId || 'Unknown'}`,
      [MODULE_TYPES.AUDIT_REPORT]: 'Compliance Audit Report',
      [MODULE_TYPES.ASSEMBLY_PACKAGE]: 'Document Assembly Package'
    };
    return titles[moduleType] || 'VERNEN™ Export';
  }

  _getSubtitle(data, moduleType) {
    return data.subtitle || `VERNEN™ Legal Compliance Platform`;
  }

  _maskPII(data) {
    const clone = JSON.parse(JSON.stringify(data));
    this._walkAndMask(clone);
    return clone;
  }

  _walkAndMask(obj) {
    for (const key of Object.keys(obj)) {
      if (this.PII_FIELDS.has(key) && typeof obj[key] === 'string') {
        obj[key] = obj[key].length > 4 ? obj[key].slice(0, 2) + '●'.repeat(obj[key].length - 4) + obj[key].slice(-2) : '●●●●';
      } else if (typeof obj[key] === 'object' && obj[key] !== null) {
        this._walkAndMask(obj[key]);
      }
    }
  }

  _flattenObj(obj, prefix = '') {
    const result = [];
    for (const [key, val] of Object.entries(obj)) {
      const path = prefix ? `${prefix}.${key}` : key;
      if (typeof val === 'object' && val !== null && !Array.isArray(val)) {
        result.push(...this._flattenObj(val, path));
      } else {
        result.push([path, val]);
      }
    }
    return result;
  }
}

// ─── FACTORY ───────────────────────────────────────────────────────
function createExportEngine(config = {}) {
  return new ExportEngine(config);
}

export { ExportEngine, createExportEngine, EXPORT_FORMATS, MODULE_TYPES };
export default createExportEngine;
